/**
 * Image Generation & Design Engine.
 *
 * Modular wrappers for cinematic photos, transparent logos, vector art, textures,
 * and UI mockups. Flow:
 *   1. Personas consult → a rigid compiled PromptBrief (the pre-compiler).
 *   2. Budget guard gate (for any generative/API call).
 *   3. Generate via official image APIs (BYO key) OR the real offline SVG designer.
 *
 * Vector kinds (logo/vector-art/ui-mockup) default to the deterministic offline
 * SVG designer — genuinely usable output with no key. Photoreal kinds
 * (cinematic-photo/texture) use a configured image provider when generative is
 * enabled, else a local placeholder.
 */
import path from "node:path";
import { ensureDirs, paths } from "../config.js";
import { log } from "../logger.js";
import { consult } from "../personas/consultation.js";
import type { AssetKind, ConsultationInput, PromptBrief } from "../personas/types.js";
import { IMAGE_PROVIDERS } from "../providers/image.js";
import { consume, breakdownLines } from "../limits/limit-manager.js";
import {
  generateLogoSvg,
  generatePhotoPlaceholderSvg,
  generateUiMockupSvg,
  generateVectorArtSvg,
} from "../assets/vector.js";
import type { EngineResult, GeneratedAsset } from "./asset-results.js";

const VECTOR_KINDS: AssetKind[] = ["logo", "vector-art", "ui-mockup"];
const PHOTO_KINDS: AssetKind[] = ["cinematic-photo", "texture"];

export interface ImageEngineInput extends ConsultationInput {
  /** Attempt an official image API (needs a configured provider + key). */
  generative?: boolean;
  /** Approve proceeding even if the budget guard flags the request. */
  approveOverBudget?: boolean;
  /** Where to save (defaults to <root>/assets). */
  outDir?: string;
  width?: number;
  height?: number;
}

export async function generateImageAsset(input: ImageEngineInput): Promise<EngineResult> {
  ensureDirs();
  const brief = consult(input);
  const outDir = input.outDir || paths.assets;
  const base = `${slug(input.subject)}_${input.assetKind}`;
  const warnings: string[] = [];

  // Vector kinds → deterministic offline SVG (the "design" half of the engine).
  if (VECTOR_KINDS.includes(input.assetKind)) {
    return offlineVector(input.assetKind, input.subject, brief, path.join(outDir, `${base}.svg`), outDir, warnings);
  }

  // Photoreal kinds → generative (budget-gated) or local placeholder.
  const { width, height } = dimsFor(brief, input);
  if (input.generative) {
    const providers = IMAGE_PROVIDERS.filter((p) => p.configured());
    if (!providers.length) {
      warnings.push("Generative requested but no image provider configured (HF_IMAGE_MODEL / REPLICATE_IMAGE_MODEL). Using placeholder.");
    }
    for (const provider of providers) {
      const gate = consume(provider.slug, 1, Boolean(input.approveOverBudget));
      if (!gate.proceeded) {
        log.warn(`Image budget gate halted for ${provider.slug}.`);
        return {
          halted: true,
          reason: gate.decision.message,
          decision: gate.decision,
          breakdown: breakdownLines(gate.decision),
          brief,
        };
      }
      const dest = path.join(outDir, `${base}.png`);
      const res = await provider.generate(brief.positivePrompt, dest, {
        width,
        height,
        steps: numParam(brief, "steps", 30),
        guidanceScale: numParam(brief, "guidanceScale", 6.5),
        negativePrompt: brief.negativePrompt,
      });
      if (res.ok) {
        return asset({
          kind: input.assetKind, dest, relDir: outDir, format: "png",
          provider: res.provider, source: "generative", license: res.license,
          attribution: res.attribution, brief, width, height, warnings,
        });
      }
      warnings.push(`${provider.slug}: ${res.note ?? "failed"}`);
    }
  }

  // Offline placeholder fallback.
  const dest = path.join(outDir, `${base}.svg`);
  const dims = generatePhotoPlaceholderSvg(input.subject, paletteOf(brief), dest, width, height);
  return asset({
    kind: input.assetKind, dest, relDir: outDir, format: "svg", provider: "offline-svg",
    source: "offline", license: "n/a (generated placeholder)", attribution: "generated placeholder",
    brief, width: dims.width, height: dims.height, warnings,
  });
}

function offlineVector(
  kind: AssetKind, subject: string, brief: PromptBrief, dest: string, relDir: string, warnings: string[],
): GeneratedAsset {
  const palette = paletteOf(brief);
  let dims: { width: number; height: number };
  if (kind === "logo") dims = generateLogoSvg(subject, palette, dest);
  else if (kind === "ui-mockup") dims = generateUiMockupSvg(subject, palette, dest);
  else dims = generateVectorArtSvg(subject, palette, dest);
  return asset({
    kind, dest, relDir, format: "svg", provider: "offline-svg", source: "offline",
    license: "MIT (generated by this tool)", attribution: "generated vector", brief,
    width: dims.width, height: dims.height, warnings,
  });
}

function asset(a: {
  kind: string; dest: string; relDir: string; format: string; provider: string;
  source: "generative" | "offline"; license: string; attribution: string; brief: PromptBrief;
  width: number; height: number; warnings: string[];
}): GeneratedAsset {
  log.info(`Image asset ready: ${a.kind} via ${a.provider} -> ${a.dest}`);
  return {
    kind: a.kind, path: a.dest, relPath: path.relative(a.relDir, a.dest), format: a.format,
    provider: a.provider, source: a.source, license: a.license, attribution: a.attribution,
    brief: a.brief, width: a.width, height: a.height, warnings: a.warnings,
  };
}

function dimsFor(brief: PromptBrief, override: { width?: number; height?: number }): { width: number; height: number } {
  if (override.width && override.height) return { width: override.width, height: override.height };
  const ar = String(brief.params.aspectRatio ?? "16:9");
  const [w, h] = ar.split(":").map((n) => Number.parseInt(n, 10));
  const base = brief.assetKind === "texture" ? 1024 : 1280;
  if (!w || !h) return { width: base, height: Math.round((base * 9) / 16) };
  return w >= h
    ? { width: base, height: Math.round((base * h) / w) }
    : { width: Math.round((base * w) / h), height: base };
}

function paletteOf(brief: PromptBrief): string[] | undefined {
  const p = brief.params.palette;
  return Array.isArray(p) ? (p as string[]) : undefined;
}

function numParam(brief: PromptBrief, key: string, dflt: number): number {
  const v = brief.params[key];
  return typeof v === "number" ? v : dflt;
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40) || "asset";
}
